version: '3.8'

services:
  api_gateway_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env.development
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
    networks:
      - external_network

networks:
  external_network:
    external: true
